### PR TITLE
Updated Readme

### LINKED ISSUE #48: Update the README
Suggest changes to the [README](../blob/main/README.md) file.

### PR DESCRIPTION
**Pull request by dhruv-porwal**
Made it more accessible for first time contributors.

# Description

Describe the changes you have made.

## Issue Resolved

Link to the issue that is resolved by this pull request goes here e.g. Fixes #09.

## Screenshots

Provide some screenshots of the changes made (if applicable).

## Checklist

Please make sure to review the following before submitting your PR:

- [x] I have read the [contribution guidelines].
- [x] I have read the code of conduct.
- [x] I have reviewed my submission in detail.

### CODE REVIEW

**Review by Rahul5430 — CHANGES_REQUESTED** [review]
Great work. Just one more thing. Update the table of contents also.

**Comment by dhruv-porwal** [comment]
> Great work. Just one more thing. Update the table of contents also.

Where sir?

**Comment by Rahul5430** [comment]
> > Great work. Just one more thing. Update the table of contents also.
> 
> Where sir?

In the README file

**Review by xeamrahul — APPROVED** [review]

**Comment by xeamrahul** [comment]
Great work.

**Review by Rahul5430 — APPROVED** [review]

**Comment by Rahul5430** [comment]
Great Work @dhruv-porwal

**Pull request merged**
